package edu.uncc.itcs.lightbulblms.controller.model.response;

import io.swagger.annotations.ApiModelProperty;

public class CourseResponse {
    @ApiModelProperty(value = "Course ID (auto-generated by database)")
    private Integer id;

    @ApiModelProperty(value = "Title of course")
    private String courseTitle;

    @ApiModelProperty(value = "Description of course")
    private String courseDescription;

    @ApiModelProperty(value = "Course code")
    private String courseCode;
}
